### PR TITLE
Remove incorrect/useless var

### PR DESCRIPTION
**Pull request by julien-f**
`vars` is already defined as it is a parameter.

### CODE REVIEW

**Comment by fvdm** [comment]
Thanks

**Comment by fvdm** [comment]
I just realized you are editing master instead of develop and I blindly merged the changes. Now I can't merge develop changes into master and everything is messed up.. sometimes I hate version control

**Comment by julien-f** [comment]
It was on purpose, because I needed those changes on master for a colleague of mine.

Do you want me to create similar PRs for `develop`?

**Comment by fvdm** [comment]
I see, no I rebuilt the repo from the Bitbucket backup and integrated the changes into develop (and then master) already and pushed to npm.

**Pull request merged**
